- file:
    path: "{{httpd_certs_dir}}"
    state: directory
    recurse: true
- copy:
    src: "/home/{{ansible_user}}/certs/{{master_fqdn}}.key"
    dest: "{{httpd_certs_dir}}/auth-proxy.key"
    remote_src: yes
- stat:
    path: "/home/{{ansible_user}}/certs/{{master_fqdn}}.chained.cer"
  register: chained_file_status
- copy:
    src: "/home/{{ansible_user}}/certs/{{master_fqdn}}.chained.cer"
    dest: "{{httpd_certs_dir}}/auth-proxy.chained.cer"
    remote_src: yes
  when: chained_file_status.stat.exists
- block:
    - copy:
        src: "/home/{{ansible_user}}/certs/{{master_fqdn}}.cer"
        dest: "{{httpd_certs_dir}}/auth-proxy.chained.cer"
        remote_src: yes
    - shell:
        cat "/home/{{ansible_user}}/certs/{{intermediate_certfile}}" >> "{{httpd_certs_dir}}/auth-proxy.chained.cer"
      when: intermediate_certfile is defined
  when: not chained_file_status.stat.exists
- file:
    path: "{{saml_certs_dir}}"
    state: directory
    recurse: true
- copy:
    src: "/home/{{ansible_user}}/certs/{{master_fqdn}}.key"
    dest: "{{saml_certs_dir}}/auth-proxy.key"
    remote_src: yes
- copy:
    src: "/home/{{ansible_user}}/certs/{{master_fqdn}}.cer"
    dest: "{{saml_certs_dir}}/auth-proxy.cer"
    remote_src: yes
- copy:
    src: "/home/{{ansible_user}}/certs/{{auth_fqdn}}.cer"
    dest: "{{saml_certs_dir}}/idp-proxy.cer"
    remote_src: yes
  when:
    - auth_fqdn is defined
    - auth_fqdn | length > 0
