- template:
    src: 20-hosts.sh.j2
    dest: /etc/vcp/rc.d/20-hosts.sh
    mode: 0755
- shell:
    cmd: grep "{{master_fqdn}}" /etc/hosts || (echo "{{manager_ipaddress}} {{master_fqdn}}" >> /etc/hosts)
