- file:
    path: "{{ home_dir }}/{{ teacher_id }}"
    state: directory
    owner: "{{teacher_id}}"
    group: "{{teacher_id}}"
    mode: 0755
- name: prepare contents directory
  file:
    path: "{{ home_dir }}/{{ teacher_id }}/{{ item }}"
    state: directory
    owner: "{{teacher_id}}"
    group: "{{teacher_id}}"
    mode: 0777
  loop:
    - info
    - textbook
