version: '3.7'
services:
{% if shibboleth_container is defined %}
  shibboleth:
    {{shibboleth_container | indent(4)}}
{% endif %}
  proxy:
    container_name: proxy
    image: {{rproxy_image_name}}
    hostname: {{moodle_url | urlsplit('hostname')}}
{% if prepare is not defined %}
    restart: always
    volumes:
      - /opt/moodle/proxy/conf:/usr/local/apache2/conf
      - /opt/moodle/cert:/usr/local/apache2/conf/cert:ro
{% endif %}
    environment:
      TZ: Asia/Tokyo
{% if shibboleth_container is not defined %}
    ports:
      - "443:443"
{% endif %}
  db-{{project_tag}}:
    container_name: db-{{project_tag}}
    image: {{db_image_name}}
{% if prepare is not defined %}
    restart: always
    volumes:
      - /opt/moodle/db-{{project_tag}}/data:/var/lib/mysql:rw
      - /opt/moodle/db-{{project_tag}}/conf/mysql:/etc/mysql
    env_file:
      - /opt/moodle/.env.db
{% endif %}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      TZ: Asia/Tokyo
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp=true
      - --log-error=/var/log/mysql/error.log
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      timeout: 10s
      retries: 10
  moodle-{{project_tag}}:
    container_name: moodle-{{project_tag}}
    image: {{moodle_image_name}}
    restart: always
{% if prepare is not defined %}
    volumes:
      - /opt/moodle/moodle-{{project_tag}}/data/moodledata:/var/data/moodledata:rw
      - /opt/moodle/moodle-{{project_tag}}/data/php:/var/www:rw
      - /opt/moodle/moodle-{{project_tag}}/conf/php.ini:/etc/php.ini
      - /opt/moodle/moodle-{{project_tag}}/conf/php.d:/etc/php.d
      - /opt/moodle/moodle-{{project_tag}}/conf/php-zts.d:/etc/php-zts.d
      - /opt/moodle/moodle-{{project_tag}}/conf/httpd/conf:/etc/httpd/conf
      - /opt/moodle/moodle-{{project_tag}}/conf/httpd/conf.d:/etc/httpd/conf.d
      - /opt/moodle/moodle-{{project_tag}}/conf/httpd/conf.modules.d:/etc/httpd/conf.modules.d
    env_file:
      - /opt/moodle/.env.db
{% else %}
    command: /bin/bash
    tty: true
    stdin_open: true
{% endif %}
    environment:
      MOODLE_VERSION: {{moodle_version}}
      MOODLE_URL: {{moodle_url}}
      MOODLE_DATAROOT: /var/data/moodledata
      MOODLE_ADMIN: {{moodle_admin_name}}
      MOODLE_ADMIN_PASSWORD: {{lookup('hashi_vault', 'secret=' + moodle_vault_path + ':password')}}
      MOODLE_SSLPROXY: 'true'
      MOODLE_DBTYPE: mariadb
      MOODLE_DBLIBRARY: native
      CNT_NAME_MYSQL: db-{{project_tag}}
      TZ: Asia/Tokyo
{% if update_project_tag is defined and clear_test_env is not defined %}
  dbtest-{{update_project_tag}}:
    container_name: dbtest-{{update_project_tag}}
{% if update_container_target is defined and update_container_target == "db" %}
    image: local/db:{{update_project_tag}}-test
{% else %}
    image: {{db_image_name}}
{% endif %}
    restart: always
    volumes:
      - /opt/moodle/dbtest-{{update_project_tag}}/data:/var/lib/mysql:rw
      - /opt/moodle/dbtest-{{update_project_tag}}/conf/mysql:/etc/mysql
    env_file:
      - /opt/moodle/.env.db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      TZ: Asia/Tokyo
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp=true
      - --log-error=/var/log/mysql/error.log
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      timeout: 10s
      retries: 10
  moodletest-{{update_project_tag}}:
    container_name: moodletest-{{update_project_tag}}
{% if update_container_target is defined and update_container_target == "moodle" %}
    image: local/moodle:{{update_project_tag}}-test
{% else %}
    image: {{moodle_image_name}}
{% endif %}
    restart: always
    env_file:
      - /opt/moodle/.env.db
    environment:
{% if update_moodle_version is defined %}
      MOODLE_VERSION: {{update_moodle_version}}
{% else %}
      MOODLE_VERSION: {{moodle_version}}
{% endif %}
      MOODLE_URL: {{moodle_url}}
      MOODLE_DATAROOT: /var/data/moodledata
      MOODLE_ADMIN: {{moodle_admin_name}}
      MOODLE_ADMIN_PASSWORD: {{lookup('hashi_vault', 'secret=' + moodle_vault_path + ':password')}}
      MOODLE_SSLPROXY: 'true'
      MOODLE_DBTYPE: mariadb
      MOODLE_DBLIBRARY: native
      CNT_NAME_MYSQL: dbtest-{{update_project_tag}}
      TZ: Asia/Tokyo
    volumes:
      - /opt/moodle/moodletest-{{update_project_tag}}/data/moodledata:/var/data/moodledata:rw
      - /opt/moodle/moodletest-{{update_project_tag}}/data/php:/var/www:rw
      - /opt/moodle/moodletest-{{update_project_tag}}/conf/php.ini:/etc/php.ini
      - /opt/moodle/moodletest-{{update_project_tag}}/conf/php.d:/etc/php.d
      - /opt/moodle/moodletest-{{update_project_tag}}/conf/php-zts.d:/etc/php-zts.d
      - /opt/moodle/moodletest-{{update_project_tag}}/conf/httpd/conf:/etc/httpd/conf
      - /opt/moodle/moodletest-{{update_project_tag}}/conf/httpd/conf.d:/etc/httpd/conf.d
      - /opt/moodle/moodletest-{{update_project_tag}}/conf/httpd/conf.modules.d:/etc/httpd/conf.modules.d
{% endif %}
