- file:
    path: "{{auth_proxy_dir}}"
    state: directory
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: true
- file:
    path: "{{certs_dir}}"
    state: directory
    owner: "{{www_data_uid}}"
    group: "{{www_data_gid}}"
  become: true
- shell:
    cmd: tr -cd 'a-z0-9' < /dev/urandom | dd bs=32 count=1 status=none > cron.secret
    chdir: "{{auth_proxy_dir}}"
    creates: cron.secret
- file:
    path: "{{auth_proxy_dir}}/cron.secret"
    mode: 0400
    state: touch
- copy:
    src: "{{idp_proxy_certificate_path}}"
    dest: "{{certs_dir}}/idp-proxy.cer"
    owner: "{{www_data_uid}}"
    group: "{{www_data_gid}}"
  become: true
  when: idp_proxy_certificate_path is defined
- name: pull auth-proxy image
  command: "docker pull {{auth_proxy_image}}"
  when: federation is not defined
- name: pull auth-proxy-fed image
  command: "docker pull {{auth_proxy_fed_image}}"
  when: federation is defined
