---
- file: path=/jupyter/admin/admin_tools state=directory
- file: path=/jupyter/admin/tools state=directory
- file: path=/jupyter/admin/textbook state=directory
- file: path=/jupyter/admin/info state=directory

- template:
    src: CoursewareHubコンテンツの配備.ipynb
    dest: "/jupyter/users/{{teacher_id}}/"
    owner: "{{teacher_id}}"
    group: users
- file:
    path: "/jupyter/users/{{teacher_id}}/.ssh"
    owner: "{{teacher_id}}"
    group: users
    mode: 0700


- file: path=/jupyter/admin/textbook state=directory mode=0777
- file: path=/jupyter/admin/info state=directory mode=0777
