services:
  base:
    image: harbor.vcloud.nii.ac.jp/vcp/moodle:1.8.1-base
    build: ./base
  moodle-common:
    image: harbor.vcloud.nii.ac.jp/vcp/moodle:common
    build:
      context: ./moodle
      dockerfile: Dockerfile.common
  moodle-73:
    image: harbor.vcloud.nii.ac.jp/vcp/moodle:php73
    build:
      context: ./moodle
      args:
        PHP_VERSION: php73
  moodle-74:
    image: harbor.vcloud.nii.ac.jp/vcp/moodle:php74
    build:
      context: ./moodle
      args:
        PHP_VERSION: php74
  moodle-80:
    image: harbor.vcloud.nii.ac.jp/vcp/moodle:php80
    build:
      context: ./moodle
      args:
        PHP_VERSION: php80
  shib:
    image: harbor.vcloud.nii.ac.jp/vcp/shibboleth:sp-3.2.2
    build: ./shibboleth
  shib-moodle:
    image: harbor.vcloud.nii.ac.jp/vcp/moodle:shibboleth-3.2.2
    build: ./moodle-shibboleth
