postgres_image: "postgres:11"
jupyterhub_image: "harbor.vcloud.nii.ac.jp/vcp/coursewarehub:jupyterhub-20210701"
auth_proxy_image: "harbor.vcloud.nii.ac.jp/vcp/coursewarehub:auth-proxy-20220222"
auth_proxy_fed_image: "harbor.vcloud.nii.ac.jp/vcp/coursewarehub:auth-proxy-fed-20210701"
idp_proxy_image: "harbor.vcloud.nii.ac.jp/vcp/coursewarehub:idp-proxy-20210701"
